CREATE TABLE tb_niveis(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(99) NOT NULL
)ENGINE=INNODB CHARSET=utf8;
CREATE TABLE tb_empresa(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cep VARCHAR(10) NOT NULL,
    email longtext NOT NULL,
    cnpj VARCHAR(15) NOT NULL
)ENGINE=INNODB CHARSET=utf8;
CREATE TABLE tb_produto(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(155) NOT NULL,
    valor FLOAT NOT NULL,
   	descricao LONGTEXT NOT NULL
)ENGINE=INNODB CHARSET=utf8;